<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12</LangVersion>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ServerGarbageCollector>false</ServerGarbageCollector>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <TieredPGO>true</TieredPGO>
    <RootNamespace>Gemx.App</RootNamespace>
    <AssemblyName>Gemx.App</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Gemx/Gemx.csproj" />
  </ItemGroup>
</Project>